kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-argocd-cluster-argocd-application-controller-knative
rules:
  - apiGroups:
      - operator.knative.dev
    resources:
      - knativeservings
      - knativeeventings
    verbs:
      - create
      - update
      - list
      - delete
      - patch
